# Generated by Django 6.1.1 on 2026-09-12 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('mle', models.CharField(choices=[('LR', 'lord'), ('KG', 'king'), ('MT', 'meta'), ('BT', 'beta'), ('MG', 'magical'), ('CH', 'child')], max_length=9)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('n', 'null')])),
                ('password', models.IntegerField()),
            ],
        ),
    ]
