# Generated by Django 6.1.1 on 2026-09-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_btc', models.IntegerField(default=0, max_length=1000000000)),
                ('coin_ss', models.IntegerField(default=0, max_length=1000000)),
                ('coin_bgc', models.IntegerField(default=0, max_length=1000000)),
                ('coin_plc', models.IntegerField(default=0, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
